### ISSUE TITLE
Have the application in French version and change the logo of the APK

### ISSUE THREAD

**Issue by QuentinMarical** [KaruzoHikari/ReplikAPP#2]
That would be possible?

[LyokoAPP-VF-master.zip](https://github.com/KaruzoDEV/LyokoAPP/files/2957189/LyokoAPP-VF-master.zip)
![Icon LyokoApp](https://user-images.githubusercontent.com/37218803/54209384-f9262a80-44dd-11e9-9130-34ce270b0995.png)

**Comment by KaruzoHikari** [comment]
I'll look into getting translations for both the app and the notifications next week.
As for the logo, DM me on Discord, @KaruzoHikari#4956

**Comment by Appryl** [comment]
Translations in french are planned, it will come very soon :)
Perhaps we can also ask for people on the IFSCL's server for other languages ?

**Comment by KaruzoHikari** [comment]
The app now has a new logo and the translations are coming in the next update, hopefully.
I'll be closing this now. Thanks!
